services:
  solar-watch:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Hurkakolbasz24?
    ports:
      - "1433:1433"
    env_file:
      - ./SolarWatch/.env
    healthcheck:
      test: [ "CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Hurkakolbasz24?", "-Q", "SELECT 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
  
  db-setup-migrate:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    command: sh -c "cat /app/SolarWatch/SolarWatch.csproj && dotnet tool install --global dotnet-ef && /root/.dotnet/tools/dotnet-ef database update --project app/SolarWatch/SolarWatch.csproj"
    depends_on:
      - solar-watch
    volumes:
      - .:/app
    env_file:
      - ./SolarWatch/.env
    environment:
      - CONNECTIONSTRING=Server=solar-watch,1433;Database=solar-watch;User Id=sa;Password=Hurkakolbasz24?;Encrypt=false;
      
  solarwatch-backend:
    image: solarwatch
    build:
      context: .
      dockerfile: SolarWatch/Dockerfile
    depends_on:
      - db-setup-migrate
    ports:
      - "8080:8080"
    env_file:
      - ./SolarWatch/.env
    environment:
      - CONNECTIONSTRING=Server=solar-watch,1433;Database=solar-watch;User Id=sa;Password=Hurkakolbasz24?;Encrypt=false;
      - JwtSettings__IssuerSigningKey=nyolchaborukalapacsesmegapatkanyirtasismelle
      - JwtSettings__ValidIssuer=apiWithAuthBackend
      - JwtSettings__ValidAudience=apiWithAuthBackend