services:
  solar-watch:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Hurkakolbasz24?
    ports:
      - "1433:1433"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Hurkakolbasz24?", "-Q", "SELECT 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
  
      
  solarwatch-backend:
    image: solarwatch
    build:
      context: .
      dockerfile: SolarWatch/Dockerfile
    depends_on:
      - solar-watch
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - CONNECTIONSTRING=Server=${DOCKER_SERVER_NAME},${DB_PORT};Database=${DB_NAME};User Id=${DB_USERNAME};Password=${DB_USER_PASSWORD};Encrypt=false;
      - JwtSettings__IssuerSigningKey=${JWTSETTINGS__ISSUERSIGNINGKEY}
      - JwtSettings__ValidIssuer=${JWTSETTINGS__VALIDISSUER}
      - JwtSettings__ValidAudience=${JWTSETTINGS__VALIDAUDIENCE}
        
  solarwatch-frontend:
    image: solarwatchfrontend
    build:
      context: ./solarwatchfrontend/solarwatch
      dockerfile: Dockerfile
    ports:
      - "5173:5173"