services:
  solar-watch:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Hurkakolbasz24?
    ports:
      - "1433:1433"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Hurkakolbasz24?", "-Q", "SELECT 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
  
  db-setup-migrate:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    command: sh -c "cat /app/SolarWatch/SolarWatch.csproj && dotnet tool install --global dotnet-ef && /root/.dotnet/tools/dotnet-ef database update --project app/SolarWatch/SolarWatch.csproj"
    depends_on:
      - solar-watch
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - CONNECTIONSTRING=Server=${DOCKER_SERVER_NAME},${DB_PORT};Database=${DB_NAME};User Id=${DB_USERNAME};Password=${DB_USER_PASSWORD};Encrypt=false;
      
  solarwatch-backend:
    image: solarwatch
    build:
      context: .
      dockerfile: SolarWatch/Dockerfile
    depends_on:
      - db-setup-migrate
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - CONNECTIONSTRING=Server=${DOCKER_SERVER_NAME},${DB_PORT};Database=${DB_NAME};User Id=${DB_USERNAME};Password=${DB_USER_PASSWORD};Encrypt=false;
      - JwtSettings__IssuerSigningKey=${JWTSETTINGS__ISSUERSIGNINGKEY}
      - JwtSettings__ValidIssuer=${JWTSETTINGS__VALIDISSUER}
      - JwtSettings__ValidAudience=${JWTSETTINGS__VALIDAUDIENCE}
        
  solarwatch-frontend:
    image: solarwatch
    build:
      context: .
      dockerfile: ./solarwatchfrontend/solarwatch/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules