FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS build-env
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["SolarWatch/SolarWatch.csproj", "SolarWatch/"]
RUN dotnet restore "SolarWatch/SolarWatch.csproj"
COPY . .
WORKDIR "/src/SolarWatch"
RUN dotnet build "SolarWatch.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "SolarWatch.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SolarWatch.dll"]
